site_name: fpx-engine
site_description: Асинхронный фреймворк для автоматизации FunPay на Python.
site_author: bymyforge

theme:
  name: material
  language: ru
  features:
    - navigation.tabs          # Удобное верхнее меню
    - navigation.sections      # Разделы в боковом меню
    - code.copy                # Кнопка копирования кода при наведении
    - navigation.top           # Кнопка "Наверх" при скролле
  palette:
    # Настройки для Светлой темы
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo          # Основной цвет (шапка, меню) - приятный сине-фиолетовый
      accent: blue             # Цвет ссылок и активных элементов
      toggle:
        icon: material/brightness-7
        name: Включить тёмную тему
    # Настройки для Тёмной темы (будет выглядеть мега-премиально)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate            # Глубокий грифельный/угольный цвет фона вместо ядовито-чёрного
      primary: black           # Чистая чёрная шапка
      accent: cyan             # Неоновые акценты для ссылок (светло-голубой)
      toggle:
        icon: material/brightness-4
        name: Включить светлую тему

nav:
  - Главная: index.md
  - Быстрый старт: quickstart.md
  - Ошибки: errors.md
  - Основной функционал:
      - Модели и типы данных: models.md
      - Обработка сообщений: chat.md
      - Работа с заказами: orders.md
      - Отзывы и фидбек: review.md
      - Профиль и баланс: profile.md
      - Управление лотами: lots.md
      - Редактор товаров: editor.md
      - Мониторинг рынка: category.md
  - Продвинутый уровень:
      - Машина состояний (FSM): fsm.md
  - Примеры скриптов: examples.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences